services:
  postgres:
    image: postgres:16-alpine
    container_name: mangmania-postgres
    environment:
      POSTGRES_DB: mangmania
      POSTGRES_USER: mangmania
      POSTGRES_PASSWORD: mangmania123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U happuser -d happshop"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mangmania-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: mangmania-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mangmania.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5051:80"  # Меняем на 5051
    depends_on:
      - postgres
    networks:
      - mangmania-network

volumes:
  postgres_data:

networks:
  mangmania-network:
    driver: bridge